### ISSUE TITLE
adapt to correct page template

### ISSUE THREAD

**Issue by coreykohn** [dojo4/dojo4.github.io#1]
Figure out and fix why the following pages are not displaying correctly:

/membership-agreement.md
/environmental_policy.md
/people-policy.md
/spin-up.md

**Comment by coreykohn** [comment]
Both of these seem fine now:

/environmental_policy.md
/people-policy.md

**Comment by coreykohn** [comment]
prolly just has something to do with .md vs .html

**Comment by lukemiller** [comment]
fixed the others
